

----

### Scorecard

<details><summary>Click to expand</summary>

#### Customized description

Scope of what has to be done.

#### Opportunity assessment

Why is this activity relevant?

#### Objectives

What we aim to achieve in this iteration.

#### Tools

Technologies, tools and products used in the Activity.

#### Operational Notes

Approach, method to progress in the Activity

</details>

----

