## Open source and digital sovereignty <a href='https://gitlab.ow2.org/ggi/my-ggi-board-test/-/issues/198' class='w3-text-grey' style='float:right'>[ GGI-A-35 ]</a>


**Customized description**

Scope of what has to be done.

**Opportunity assessment**

Why is this activity relevant?

**Objectives**

What we aim to achieve in this iteration.

**Tools**

Technologies, tools and products used in the Activity.

**Operational Notes**

Approach, method to progress in the Activity


## Support open source communities <a href='https://gitlab.ow2.org/ggi/my-ggi-board-test/-/issues/167' class='w3-text-grey' style='float:right'>[ GGI-A-30 ]</a>


**Customized description**

Scope of what has to be done.

**Opportunity assessment**

Why is this activity relevant?

**Objectives**

What we aim to achieve in this iteration.
- [x] objective 1
- [x] objective 2
- [ ] objective 3

**Tools**

Technologies, tools and products used in the Activity.

**Operational Notes**

Approach, method to progress in the Activity


## HR perspective <a href='https://gitlab.ow2.org/ggi/my-ggi-board-test/-/issues/164' class='w3-text-grey' style='float:right'>[ GGI-A-28 ]</a>


**Customized description**

Scope of what has to be done.

**Opportunity assessment**

Why is this activity relevant?

**Objectives**

What we aim to achieve in this iteration.
- [ ] objective 1
- [x] objective 2
- [ ] objective 3

**Tools**

Technologies, tools and products used in the Activity.

**Operational Notes**

Approach, method to progress in the Activity


## Belong to the open source community <a href='https://gitlab.ow2.org/ggi/my-ggi-board-test/-/issues/163' class='w3-text-grey' style='float:right'>[ GGI-A-27 ]</a>


**Customized description**

Scope of what has to be done.

**Opportunity assessment**

Why is this activity relevant?

**Objectives**

What we aim to achieve in this iteration.
- [ ] objective 1
- [x] objective 2
- [x] objective 3

**Tools**

Technologies, tools and products used in the Activity.

**Operational Notes**

Approach, method to progress in the Activity

