* [Open source enabling digital transformation](https://gitlab.ow2.org/ggi/my-ggi-board-test/-/issues/200) (GGI-A-37). <br />
  Tasks: 0 done / 0 total.
  <br /><br />
* [Support open source communities](https://gitlab.ow2.org/ggi/my-ggi-board-test/-/issues/167) (GGI-A-30). <br />
  Tasks: 2 done / 3 total.
  <div class="w3-light-grey w3-round">
    <div class="w3-container w3-blue w3-round" style="width:66%">66%</div>
  </div><br />
* [HR perspective](https://gitlab.ow2.org/ggi/my-ggi-board-test/-/issues/164) (GGI-A-28). <br />
  Tasks: 1 done / 3 total.
  <div class="w3-light-grey w3-round">
    <div class="w3-container w3-blue w3-round" style="width:33%">33%</div>
  </div><br />
* [Belong to the open source community](https://gitlab.ow2.org/ggi/my-ggi-board-test/-/issues/163) (GGI-A-27). <br />
  Tasks: 2 done / 3 total.
  <div class="w3-light-grey w3-round">
    <div class="w3-container w3-blue w3-round" style="width:66%">66%</div>
  </div><br />