## Open source enabling digital transformation <a href='https://gitlab.ow2.org/ggi/my-ggi-board-test/-/issues/200' class='w3-text-grey' style='float:right'>[ GGI-A-37 ]</a>


  Tasks: 0 done / 0 total.
  <br /><br />

**Customized description**

Scope of what has to be done.

**Opportunity assessment**

Why is this activity relevant?

**Objectives**

What we aim to achieve in this iteration.

**Tools**

Technologies, tools and products used in the Activity.

**Operational Notes**

Approach, method to progress in the Activity


## Support open source communities <a href='https://gitlab.ow2.org/ggi/my-ggi-board-test/-/issues/167' class='w3-text-grey' style='float:right'>[ GGI-A-30 ]</a>


  Tasks: 2 done / 3 total.
  <div class="w3-light-grey w3-round">
    <div class="w3-container w3-blue w3-round" style="width:66%">66%</div>
  </div><br />

**Customized description**

Scope of what has to be done.

**Opportunity assessment**

Why is this activity relevant?

**Objectives**

What we aim to achieve in this iteration.
- [x] objective 1
- [x] objective 2
- [ ] objective 3

**Tools**

Technologies, tools and products used in the Activity.

**Operational Notes**

Approach, method to progress in the Activity


## HR perspective <a href='https://gitlab.ow2.org/ggi/my-ggi-board-test/-/issues/164' class='w3-text-grey' style='float:right'>[ GGI-A-28 ]</a>


  Tasks: 1 done / 3 total.
  <div class="w3-light-grey w3-round">
    <div class="w3-container w3-blue w3-round" style="width:33%">33%</div>
  </div><br />

**Customized description**

Scope of what has to be done.

**Opportunity assessment**

Why is this activity relevant?

**Objectives**

What we aim to achieve in this iteration.
- [ ] objective 1
- [x] objective 2
- [ ] objective 3

**Tools**

Technologies, tools and products used in the Activity.

**Operational Notes**

Approach, method to progress in the Activity


## Belong to the open source community <a href='https://gitlab.ow2.org/ggi/my-ggi-board-test/-/issues/163' class='w3-text-grey' style='float:right'>[ GGI-A-27 ]</a>


  Tasks: 2 done / 3 total.
  <div class="w3-light-grey w3-round">
    <div class="w3-container w3-blue w3-round" style="width:66%">66%</div>
  </div><br />

**Customized description**

Scope of what has to be done.

**Opportunity assessment**

Why is this activity relevant?

**Objectives**

What we aim to achieve in this iteration.
- [ ] objective 1
- [x] objective 2
- [x] objective 3

**Tools**

Technologies, tools and products used in the Activity.

**Operational Notes**

Approach, method to progress in the Activity

