* [Open source enabling digital transformation](https://gitlab.ow2.org/ggi/my-ggi-board-test/-/issues/50) (50).
* [Open source enabling innovation](https://gitlab.ow2.org/ggi/my-ggi-board-test/-/issues/49) (49).
* [Support open source communities](https://gitlab.ow2.org/ggi/my-ggi-board-test/-/issues/42) (42).
* [Engage with open source projects](https://gitlab.ow2.org/ggi/my-ggi-board-test/-/issues/41) (41).
* [Contribute to open source projects](https://gitlab.ow2.org/ggi/my-ggi-board-test/-/issues/37) (37).
* [Open source competency growth](https://gitlab.ow2.org/ggi/my-ggi-board-test/-/issues/27) (27).