
> Congrats! 

You have just setup your own Good Governance Initiative dashboard. You may now:

* Start selecting activities from the list and update their progress labels from 'Not Started' to 'In Progress'.

You can also note these interesting links:
* Communicate this URL to your teams: [GGI_PAGES_URL].
* Communicate this URL to your teams: [GGI_ACTIVITIES_URL].


Note: this message will disappear once you start making progress on tasks.

