* [C-Level awareness](https://gitlab.ow2.org/ggi/my-ggi-board-test/-/issues/197) (GGI-A-34). <br />
  Tasks: 0 done / 0 total.
  <br /><br />
* [Open source enabling innovation](https://gitlab.ow2.org/ggi/my-ggi-board-test/-/issues/174) (GGI-A-36). <br />
  Tasks: 3 done / 3 total.
  <div class="w3-light-grey w3-round">
    <div class="w3-container w3-blue w3-round" style="width:100%">100%</div>
  </div><br />
* [Open source and digital sovereignty](https://gitlab.ow2.org/ggi/my-ggi-board-test/-/issues/173) (GGI-A-35). <br />
  Tasks: 3 done / 3 total.
  <div class="w3-light-grey w3-round">
    <div class="w3-container w3-blue w3-round" style="width:100%">100%</div>
  </div><br />
* [Contribute to open source projects](https://gitlab.ow2.org/ggi/my-ggi-board-test/-/issues/162) (GGI-A-26). <br />
  Tasks: 3 done / 3 total.
  <div class="w3-light-grey w3-round">
    <div class="w3-container w3-blue w3-round" style="width:100%">100%</div>
  </div><br />