## C-Level awareness <a href='https://gitlab.ow2.org/ggi/my-ggi-board-test/-/issues/197' class='w3-text-grey' style='float:right'>[ GGI-A-34 ]</a>


**Customized description**

Scope of what has to be done.

**Opportunity assessment**

Why is this activity relevant?

**Objectives**

What we aim to achieve in this iteration.

**Tools**

Technologies, tools and products used in the Activity.

**Operational Notes**

Approach, method to progress in the Activity


## Open source enabling innovation <a href='https://gitlab.ow2.org/ggi/my-ggi-board-test/-/issues/174' class='w3-text-grey' style='float:right'>[ GGI-A-36 ]</a>


**Customized description**

Scope of what has to be done.

**Opportunity assessment**

Why is this activity relevant?

**Objectives**

What we aim to achieve in this iteration.
- [x] objective 1
- [x] objective 2
- [x] objective 3

**Tools**

Technologies, tools and products used in the Activity.

**Operational Notes**

Approach, method to progress in the Activity


## Open source and digital sovereignty <a href='https://gitlab.ow2.org/ggi/my-ggi-board-test/-/issues/173' class='w3-text-grey' style='float:right'>[ GGI-A-35 ]</a>


**Customized description**

Scope of what has to be done.

**Opportunity assessment**

Why is this activity relevant?

**Objectives**

What we aim to achieve in this iteration.
- [x] objective 1
- [x] objective 2
- [x] objective 3

**Tools**

Technologies, tools and products used in the Activity.

**Operational Notes**

Approach, method to progress in the Activity

