## Open source enabling digital transformation

Link to activitiy in board: https://gitlab.ow2.org/ggi/my-ggi-board-test/-/issues/50 

> "Digital Transformation is the adoption of digital technology to transform services or businesses, through replacing non-digital or manual processes with digital processes or replacing older digital technology with newer digital technology." (Wikipedia)


## Open source enabling innovation

Link to activitiy in board: https://gitlab.ow2.org/ggi/my-ggi-board-test/-/issues/49 

> Innovation is the practical implementation of ideas that result in the introduction of new goods or services or improvement in offering goods or services.
>
> &mdash; <cite>Schumpeter, Joseph A.</cite>


## Support open source communities

Link to activitiy in board: https://gitlab.ow2.org/ggi/my-ggi-board-test/-/issues/42 

This activity is about engaging with institutional representatives of the open source world. 


## Engage with open source projects

Link to activitiy in board: https://gitlab.ow2.org/ggi/my-ggi-board-test/-/issues/41 

This activity is about committing significant contributions to some OSS projects that are important to you. Contributions are scaled up and committed at the organisation level (not personal level as in #26). They can take several forms, from direct funding to resources allocation (e.g. people, servers, infrastructure, communication, etc.), as long as they benefit the project or ecosystem sustainably and efficiently. 


## Contribute to open source projects

Link to activitiy in board: https://gitlab.ow2.org/ggi/my-ggi-board-test/-/issues/37 

Contributing to open source projects that are freely used is one of the key principles of good governance. The point is to avoid being a simple passive consumer and give back to the projects. When people add a feature or fix a bug for their own purpose, they should make it generic enough to contribute to the project. Developers must be allowed time for contributions. 


## Open source competency growth

Link to activitiy in board: https://gitlab.ow2.org/ggi/my-ggi-board-test/-/issues/27 

This activity is about planning and initiating technical abilities and early experience with OSS once an inventory has been conducted (#17). It is also the opportunity to start establishing a basic, lightweight skills development roadmap.
- Identify what the required skills and training are.
- Set up a pilot project to kick start the approach, learn from doing, establish a first achievement milestone.
- Capitalise on lessons learned and build a body of knowledge.
- Start identifying and documenting the next steps for broader adoption. 
- Elaborate a strategy over the next few months or a year to engage management and financial support.

