## Promote open source development best practices

Link to activitiy in board: https://gitlab.ow2.org/ggi/my-ggi-board-test/-/issues/36 

This activity is about defining, actively promoting and implementing open source best practices within the development teams.


## Run code reviews

Link to activitiy in board: https://gitlab.ow2.org/ggi/my-ggi-board-test/-/issues/35 

Code review is a routine task involving manual and/or automated review of an application's source code before releasing a product or delivering a project to the customer. In the case of open-source software, code review is more than just about catching errors opportunistically; it is an integrated approach to collaborative development carried out at the team level. 


## Inventory of open source skills and resources

Link to activitiy in board: https://gitlab.ow2.org/ggi/my-ggi-board-test/-/issues/26 

At any stage, from a management perspective, it is useful to have a mapping, an inventory of open source resources, assets, usage and their status, as well as potential needs and available solutions. It also includes assessing the required effort and skills to fill the gap. 

